### ISSUE TITLE
Plugin Features

### ISSUE THREAD

**Issue by lloyd-teamtangible** [TangibleInc/framework#2]
Hi @eliot-akira!

Could you please help me understand why the plugin features from the old framework are not included in the new one? I’m in the process of upgrading some plugins and haven’t been able to find the plugin features section. If there’s something I might be overlooking, your guidance would be very helpful.

Thank you!

**Comment by eliot-akira** [comment]
Hi @lloyd-teamtangible - There are some features from the old framework that haven't been ported to the new one yet.

I see the "Plugin Features" is a [small file](https://bitbucket.org/tangibleinc/tangible-plugin-framework/src/master/plugin/features.php), so it shouldn't take me too long to migrate over. I'll write here when it's ready.

There's no documentation at all, only placeholder `readme.md` for each module - so please feel free to open new issues if you have any questions, or pull requests if you'd like to contribute. Thanks!

**Comment by lloyd-teamtangible** [comment]
Hi, @eliot-akira

Sorry for kind late reply and also thanks for letting me know about this!  I can wait for the migration of the 'Plugin Features.' It’s not urgent, but it’ll be great to have. And of course, I’ll let you know if I have any questions.

Thanks, Eliot!

**Comment by eliot-akira** [comment]
So I've added the feature and documented it briefly.

![tangible-plugin-features-settings-page](https://github.com/user-attachments/assets/ed8ba23f-54ee-4209-ac0b-9c2515114b20)

https://github.com/TangibleInc/framework/tree/main/plugin#readme

It works a little differently than before. I simplified it so there's no concept of feature groups. Also, previously the "Features" tab in the plugin settings page was added automatically, but now the plugin must add it themselves when they're registering settings config. This way it's up to the plugin where to put it.

---

>  I’m in the process of upgrading some plugins

Could you tell me which ones? Maybe there's more I can do in the new framework to ease the upgrade process.

I noticed there's another missing functionality, a way to **register plugin dependencies**. The framework used to automatically check and show an admin notification if all dependencies were not installed and active. That was convenient, so I'll look into adding it.

**Comment by lloyd-teamtangible** [comment]
Awesome, thanks for looking into this!

> Could you tell me which ones? Maybe there's more I can do in the new framework to ease the upgrade process.
I'm planning to build a new plugin for our client and want to use the plugin features. This is the only repo that seems like it might offer some useful ideas: https://bitbucket.org/tangibleinc/tangible-tweaks-for-learndash/src/master/. And it's uses the old framework.

**Comment by eliot-akira** [comment]
> planning to build a new plugin

I'm preparing a new command for quickly starting new projects based on "presets". Would you be willing to try it?

- https://github.com/TangibleInc/create

It's a single command that asks a few questions and sets up a new folder with initial files.

```sh
npm create tangible@latest
```

It's an early "alpha" version, still a work in progress. For example, the plugin release and update lifecycle is not complete yet. I want to prepare a GitHub Actions workflow, where every tagged version is automatically built as a zip package and published to the plugin update server. We can discuss further in the `create` repository, if you'd like.

I'll close this issue since the "Plugin Features" feature has been ported from the old framework. Please feel free to create new issues as needed. I'm hoping with your feedback we can improve various parts of the plugin development process.
