### ISSUE TITLE
L&L Template with Local Variable acf_oembed or wysiwyg  is not being rendered

### ISSUE THREAD

**Issue by ghen-arvesu** [TangibleInc/framework#6]
HI @eliot-akira a team member reported the following:

If I tried to use a template and add a value with tag in the local variable of a template, it didn't render the code. 

`<Template name=modal image="{Field acf_image=best_industry_focus_image field=url}" content="{Field acf_oembed=best_industry_focus_video}" />
`
If I want to use this template by adding an embed custom field it renders the < into { . 

`{iframe title="What Is WordPress?" width="640" height="360" src="https://www.youtube.com/embed/cT4NlI00hMw?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen}{/iframe}`

We're also experiencing this issue if we want to use a template with local variable in wysiwyg block control.

**Comment by eliot-akira** [comment]
I see, I think the issue is that these fields contain HTML which cannot be passed safely in tag attributes like `content` here.

This is a limitation of the HTML syntax, and L&L provides partial support by replacing `{}` with `<>`. But this encode/decode process is primitive, it doesn't work well for larger complex HTML like the OEmbed and WYSIWYG field.

Ideally this needs a better syntax and logic, but I haven't found a good solution yet. Maybe it should be noted in the documentation that only simple values are recommended for passing in a tag attribute using the `{}` syntax.

As a workaround, I'd suggest using a global variable to pass HTML content to a template.

```html
<Set modal_content>
  <Field acf_oembed=best_industry_focus_video />
</Set>
<Template name=modal />
```

And to use it in the template:

```html
<Get modal_content />
```

This way, the HTML content doesn't need to go through a tag attribute.

---

By the way, for issues and questions with the L&L template system, would you mind posting in the following repository?

- https://github.com/TangibleInc/template-system/issues

That one is the heart of L&L and Tangible Blocks. This current repo, [framework](https://github.com/TangibleInc/framework), contains the Framework module which has more general-purpose features for all Tangible plugins to use.

**Comment by ghen-arvesu** [comment]
yep! ofc! thank you so much!

**Comment by eliot-akira** [comment]
OK, I've made a note to document some of the info here:

- TangibleInc/loops-and-logic-docs#5
